### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by bjsi** [00x0101101/RN_ObjectOrientedNoting#1]
Hey the idea for the plugin looks really interesting, but I can't understand how to use :sweat_smile:. Could you add some very simple examples for each keyword (partial, pointer) to the README? The instanceOf explanation is good, just the partial and pointer examples could be simplified. Maybe a simple real world example would help?

**Comment by bjsi** [comment]
I approved your plugin now so it should be available in the plugin marketplace :1st_place_medal:. I recommend joining the RemNote discord channel so you can announce your plugin: https://bit.ly/RemNoteDiscord

**Comment by 00x0101101** [comment]
I have a better depiction(maybe) about the whole system

**Comment by bjsi** [comment]
Thanks that's great!
